export const mockDataObject = {
    mockStringWithTags:
        '<span>Customer</span> <br><br> Donec tincidunt tempor quam, non mollis quam finibus nec. Quisque finibus consequat felis vel pretium. Aliquam gravida nisi vel convallis ultricies. Integer ante sapien, consequat et dolor vel.',
    stringToDecode:
        '2022%20software%20development%20trends%20explained%20with%20benefits',
    correctResultForFilteredByTagFirstScenario: [
        {
            author: 'William Pond',
            blogTitle: 'SowtvareBlogTitle',
            countOfTheViews: '403 Views',
            firstContentPart: 'FirstContentPart',
            id: 3,
            image: './images/article4.png',
            publishDate: 'PublishDate',
            secondContentPart: 'SecondContentPart',
            separateParagraph: 'SeparateParagraph',
            share: 'Share',
            tagsArray: ['Future', 'Media', 'App'],
            tagsTitle: 'Tags',
        },
        {
            author: 'William Pond',
            blogTitle: 'SowtvareBlogTitle',
            countOfTheViews: '308 Views',
            firstContentPart: 'FirstContentPart',
            id: 1,
            image: './images/article2.png',
            publishDate: 'PublishDate',
            secondContentPart: 'SecondContentPart',
            separateParagraph: 'SeparateParagraph',
            share: 'Share',
            tagsArray: ['App', 'Information security'],
            tagsTitle: 'Tags',
        },
    ],
    correctResultForFilteredByTagSecondScenario: [
        {
            author: 'William Pond',
            blogTitle: 'SowtvareBlogTitle',
            countOfTheViews: '401 Views',
            firstContentPart: 'FirstContentPart',
            id: 2,
            image: './images/article3.png',
            publishDate: 'PublishDate',
            secondContentPart: 'SecondContentPart',
            separateParagraph: 'SeparateParagraph',
            share: 'Share',
            tagsArray: ['CIO', 'Team', 'Managment'],
            tagsTitle: 'Tags',
        },
        {
            author: 'William Pond',
            blogTitle: 'SowtvareBlogTitle',
            countOfTheViews: '303 Views',
            firstContentPart: 'FirstContentPart',
            id: 8,
            image: './images/article9.png',
            publishDate: 'PublishDate',
            secondContentPart: 'SecondContentPart',
            separateParagraph: 'SeparateParagraph',
            share: 'Share',
            tagsArray: ['Big Data', 'Data analytics'],
            tagsTitle: 'Tags',
        },
        {
            author: 'William Pond',
            blogTitle: 'SowtvareBlogTitle',
            countOfTheViews: '100 Views',
            firstContentPart: 'FirstContentPart',
            id: 4,
            image: './images/article5.png',
            publishDate: 'PublishDate',
            secondContentPart: 'SecondContentPart',
            separateParagraph: 'SeparateParagraph',
            share: 'Share',
            tagsArray: ['Proxy', 'Data analytics'],
            tagsTitle: 'Tags',
        },
    ],
    correctResultOfRelatedPostsFirstScenario: [
        {
            author: 'William Pond',
            blogTitle: 'SowtvareBlogTitle',
            countOfTheViews: '100 Views',
            firstContentPart: 'FirstContentPart',
            id: 4,
            image: './images/article5.png',
            publishDate: 'PublishDate',
            secondContentPart: 'SecondContentPart',
            separateParagraph: 'SeparateParagraph',
            share: 'Share',
            tagsArray: ['Proxy', 'Data analytics'],
            tagsTitle: 'Tags',
        },
        {
            author: 'William Pond',
            blogTitle: 'SowtvareBlogTitle',
            countOfTheViews: '503 Views',
            firstContentPart: 'FirstContentPart',
            id: 5,
            image: './images/article6.png',
            publishDate: 'PublishDate',
            secondContentPart: 'SecondContentPart',
            separateParagraph: 'SeparateParagraph',
            share: 'Share',
            tagsArray: ['Proxy', 'Data', 'Big data'],
            tagsTitle: 'Tags',
        },
        {
            author: 'William Pond',
            blogTitle: 'SowtvareBlogTitle',
            countOfTheViews: '303 Views',
            firstContentPart: 'FirstContentPart',
            id: 7,
            image: './images/article8.png',
            publishDate: 'PublishDate',
            secondContentPart: 'SecondContentPart',
            separateParagraph: 'SeparateParagraph',
            share: 'Share',
            tagsArray: ['Proxy', 'Information security'],
            tagsTitle: 'Tags',
        },
    ],
    correctResultOfRelatedPostsScenarioScenario: [
        {
            author: 'William Pond',
            blogTitle: 'SowtvareBlogTitle',
            countOfTheViews: '308 Views',
            firstContentPart: 'FirstContentPart',
            id: 1,
            image: './images/article2.png',
            publishDate: 'PublishDate',
            secondContentPart: 'SecondContentPart',
            separateParagraph: 'SeparateParagraph',
            share: 'Share',
            tagsArray: ['App', 'Information security'],
            tagsTitle: 'Tags',
        },
        {
            author: 'William Pond',
            blogTitle: 'SowtvareBlogTitle',
            countOfTheViews: '403 Views',
            firstContentPart: 'FirstContentPart',
            id: 3,
            image: './images/article4.png',
            publishDate: 'PublishDate',
            secondContentPart: 'SecondContentPart',
            separateParagraph: 'SeparateParagraph',
            share: 'Share',
            tagsArray: ['Future', 'Media', 'App'],
            tagsTitle: 'Tags',
        },
        {
            author: 'William Pond',
            blogTitle: 'SowtvareBlogTitle',
            countOfTheViews: '100 Views',
            firstContentPart: 'FirstContentPart',
            id: 4,
            image: './images/article5.png',
            publishDate: 'PublishDate',
            secondContentPart: 'SecondContentPart',
            separateParagraph: 'SeparateParagraph',
            share: 'Share',
            tagsArray: ['Proxy', 'Data analytics'],
            tagsTitle: 'Tags',
        },
    ],
};
