const mockDataObject = {
    mockPopularPosts: [
        {
            id: '5',
            image: './images/article6.png',
            publishDate: 'PublishDate',
            author: 'William Pond',
            blogTitle: 'SowtvareBlogTitle',
            firstContentPart: 'FirstContentPart',
            separateParagraph: 'SeparateParagraph',
            secondContentPart: 'SecondContentPart',
            countOfTheViews: '503 Views',
            share: 'Share',
            tagsTitle: 'Tags',
            tagsArray: ['Proxy', 'Data'],
        },
        {
            id: '0',
            image: './images/article1.png',
            publishDate: 'PublishDate',
            author: 'William Pond',
            blogTitle: 'SowtvareBlogTitle',
            firstContentPart: 'FirstContentPart',
            separateParagraph: 'SeparateParagraph',
            secondContentPart: 'SecondContentPart',
            countOfTheViews: '421 Views',
            share: 'Share',
            tagsTitle: 'Tags',
            tagsArray: ['Data', 'Future'],
        },
        {
            id: '3',
            image: './images/article4.png',
            publishDate: 'PublishDate',
            author: 'William Pond',
            blogTitle: 'SowtvareBlogTitle',
            firstContentPart: 'FirstContentPart',
            separateParagraph: 'SeparateParagraph',
            secondContentPart: 'SecondContentPart',
            countOfTheViews: '403 Views',
            share: 'Share',
            tagsTitle: 'Tags',
            tagsArray: ['Future', 'Media', 'App'],
        },
    ],
};

export default mockDataObject;
