export enum valuesOfTheSettings {
    DEFAULT_APP_LANGUAGE = 'en',
    HOME = 'Home',
    SOLUTIONS = 'Solutions',
    PAGES = 'Pages',
    ELEMENTS = 'Elements',
    BLOG = 'Blog',
    CONTACT = 'Contact',
    WATCH_THE_DEMO = 'Watch the demo',
    FIND_POWER = 'Find power',
    ENSOME = 'Ensome',
    HEROES_SECTION_DESCRIPTION = 'HeroesSectionDescription',
    LEARN_MORE = 'Learn more',
    NEWEST_PLATFORM_START = 'Newest platform start',
    NEWEST_PLATFORM_MIDDLE = 'Newest platform middle',
    NEWEST_PLATFORM_END = 'Newest platform end',
    NEWEST_PLATFORM_DESCRIPTION = 'NewestPlatformDescription',
    DISCOVER_MORE = 'Discover more',
    NEW_SOLUTIONS = 'New Solutions',
    NEW_SOLUTIONS_DESCRIPTION = 'New Solutions Description',
    OVERVIEW_TITLE = 'OverviewTitle',
    OVERVIEW_DESCRIPTION = 'OverviewDescription',
    PROJECT_EXECUTED = 'ProjectExecuted',
    S_CUSTOMERS = 'SatisfiedCustomers',
    DATA_MANAGEMENT = 'DataManagement',
    BENEFITS_TITLE = 'BenefitsTitle',
    BENEFITS_DESCRIPTION = 'BenefitsDescription',
    MACHINE_LEARNING_TITLE = 'MachineLearningTitle',
    MACHINE_LEARNING_DESCRIPTION = 'MachineLearningDescription',
    EMBED_ANALYTICS_TITLE = 'EmbedAnalyticsTitle',
    EMBED_ANALYTICS_DESCRIPTION = 'EmbedAnalyticsDescription',
    ACCESS_CONTROL_TITLE = 'AccessControlTitle',
    ACCESS_CONTROL_DESCRIPTION = 'AccessControlDescription',
    DATA_ANALYTICS_TITLE = 'DataAnalyticsTitle',
    DATA_ANALYTICS_DESCRIPTION = 'DataAnalyticsDescription',
    TESTIMONIALS = 'Testimonials',
    OUR_PRICING = 'OurPricing',
    FREE_TRIAL = 'FreeTrial',
    LITE = 'Lite',
    BASIC = 'Basic',
    FOR_ENTERPRISES = 'ForEnterprises',
    FOR_SMALL_TEAMS = 'ForSmallTeams',
    COMUNITY_SUPPORT = 'CommunitySupport',
    FOR_MIDDLE_TEAMS = 'ForMiddleTeams',
    INDIVIDUAL_SUPPORT = 'IndividualSupport',
    INDIVIDUAL_DATA = 'IndividualData',
    FOR_BIG_TEAMS = 'ForBigTeams',
    INDIVIDUAL_DATA120 = 'IndividualData120',
    ADVANCED_PERMISSIONS = 'AdvancedPermissions',
    UNLIMITED_TEAMS = 'UnlimitedTeams',
    UNLIMITED_DATA = 'UnlimitedData',
    DATA_HISTORY = 'DataHistory',
    AUDIT_LOG = 'AuditLog',
    ALL_FUNCTIONS = 'AllFunctions',
    CHOOSE_PLAN = 'ChoosePlan',
    PUBLISH_DATE = 'PublishDate',
    SOFTWARE_BLOG_TITLE = 'SowtvareBlogTitle',
    FIRST_CONTENT_PART = 'FirstContentPart',
    SEPARATE_PARAGRAPH = 'SeparateParagraph',
    SECOND_CONTENT_PART = 'SecondContentPart',
    VIEWS = 'Views',
    SHARE = 'Share',
    TAGS = 'Tags',
    READ_MORE = 'ReadMore',
}

export enum numberEnums {
    MONTH_ON_THE_YEAR = 12,
}

export const envConstants = {
    PAYPAL_ID: process.env.PAYPAL_ID,
    PAYPAL_SECRET: process.env.PAYPAL_SECRET,
};
