import { dictionary } from '@/types/constants';

const {
    DATA_ANALYTICS,
    DATA_MINING,
    BUSINESS_INTELLIGENCE,
    EXPLORATORY_DATA_ANALYSIS,
    CONFIRMATORY_DATA_ANALYSIS,
    PREDICTIVE_ANALYTICS,
    DATA_VISUALIZATION,
} = dictionary;

const faqData = [
    DATA_ANALYTICS,
    DATA_MINING,
    BUSINESS_INTELLIGENCE,
    EXPLORATORY_DATA_ANALYSIS,
    CONFIRMATORY_DATA_ANALYSIS,
    PREDICTIVE_ANALYTICS,
    DATA_VISUALIZATION,
];

export default faqData;
